### ISSUE TITLE
Мод джаста на 1.21

### ISSUE THREAD

**Issue by MrMasrozYTLIVE** [N1zard/N1zard#1]
Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21

**Comment by N1zard** [comment]
> Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21

ёуууу спасибо бро!

**Comment by N1zard** [comment]
> Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21

А ты давно моды делаешь? Или только мод портировал?

**Comment by MrMasrozYTLIVE** [comment]
> > Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21
> 
> А ты давно моды делаешь? Или только мод портировал?

ну модами я особо не занимался никогда, не было идей

**Comment by N1zard** [comment]
> > > Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21
> > 
> > 
> > А ты давно моды делаешь? Или только мод портировал?
> 
> ну модами я особо не занимался никогда, не было идей

но знания есть?

**Comment by MrMasrozYTLIVE** [comment]
> > > > Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21
> > > 
> > > 
> > > А ты давно моды делаешь? Или только мод портировал?
> > 
> > 
> > ну модами я особо не занимался никогда, не было идей
> 
> но знания есть?

Ага. На джаве всякую ерунду делаю уже пожалуй года так 3

**Comment by N1zard** [comment]
> а джаве всякую ерунду делаю уже пожалуй года так 3

Не подскажешь где можно найти всё, что позволяет фабрик? Просто у меня и идеи есть и желание. Джаву я вроде как +- изучил а как мод сам разрабатывать так и не понимаю

**Comment by MrMasrozYTLIVE** [comment]
> > а джаве всякую ерунду делаю уже пожалуй года так 3
> 
> Не подскажешь где можно найти всё, что позволяет фабрик? Просто у меня и идеи есть и желание. Джаву я вроде как +- изучил а как мод сам разрабатывать так и не понимаю

https://fabricmc.net/wiki/start

**Comment by MrMasrozYTLIVE** [comment]
> > Ну, другого способа связаться я не нашел, так что - https://github.com/MrMasrozYTLIVE/CatTeleportMod-Fabric/releases/tag/1.21
> 
> ёуууу спасибо бро!

Я кстати его выложил на [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/catteleportmod) и [Modrinth](https://modrinth.com/mod/catteleportmod)
А так же я слегка переработал описание и вики мода если интересно

**Comment by N1zard** [comment]
Интересно. Спасибо! (И ещё. Я бы выделил фразу Twitch Streamer JustS гиперссылкой. Тк он сам недавно ник поменял и его могут попросту не найти. Но ты сам решай)

**Comment by MrMasrozYTLIVE** [comment]
> Интересно. Спасибо! (И ещё. Я бы выделил фразу Twitch Streamer JustS гиперссылкой. Тк он сам недавно ник поменял и его могут попросту не найти. Но ты сам решай)

Его в гугле можно спокойно найти, у него ник JustS_JS, а этот ник упоминается там

**Comment by MrMasrozYTLIVE** [comment]
Qq, там обнова вышла, я переписал конфиг и команды (внутренности, для пользователей никакой по итогу разницы), а так же добавил бинды

**Comment by N1zard** [comment]
q, я вижу обновы через mod menu. не надо по любому поводу писать

**Comment by MrMasrozYTLIVE** [comment]
> q, я вижу обновы через mod menu. не надо по любому поводу писать

А, ахахах. Не знал что там обновы модов показывает, не использую эту фичу
